<?php if (isset($messages['success'])): ?>
    <div style="color: green">
        <ul>
        <?php foreach ($messages['success'] as $message): ?>
            <li><?= $message ?></li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<div>
    <form action="/users" method="get">
        <label>
            Поиск пользователей:
            <input type="text" name="search" value="">
        </label>
        <input type="submit" value="Поиск">
    </form>
</div>
<div>
    <ul>
        <?php foreach ($users as ['id' => $id, 'nickname' => $nickname, 'email' => $email]) : ?>
        <li>
            <a href="/users/<?= $id ?>"><?= htmlspecialchars($nickname) ?></a>
            (<?= htmlspecialchars($email) ?>)
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<hr>
<div>
    <?php if (!isset($_SESSION['email'])) : ?>
        <p>Nothing to display, sorry :( (<a href="/login">login</a>)</p>
    <?php else : ?>
        <form action="/logout" method="post">
            <input type="hidden" name="_METHOD" value="DELETE">
            <input type="submit" value="Logout">
        </form>
    <?php endif; ?>
</div>
