<?php if (isset($messages['success'])): ?>
    <div style="color: green">
        <ul>
        <?php foreach ($messages['success'] as $message): ?>
            <li><?= $message ?></li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<div>
    <form action="/users" method="get">
        <label>
            Поиск пользователей:
            <input type="text" name="search" value="">
        </label>
        <input type="submit" value="Поиск">
    </form>
</div>
<div>
    <ul>
        <?php foreach ($users as ['id' => $id, 'nickname' => $nickname]) : ?>
        <li><a href="/users/<?= $id ?>"><?= $nickname ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
